{{#justfile}}# @mason: flutter_rust_bridge

# When 'just' is called with no arguments,
# these recipes are run by default.
default: gen lint

# Add new recipes to these meta-recipes as you add new modules.
gen:{{#tasks}} gen_{{..snakeCase()}}{{/tasks}}
lint:{{#tasks}} lint_{{..snakeCase()}}{{/tasks}}
    dart fmt .
clean:{{#tasks}} clean_{{..snakeCase()}}{{/tasks}}
    flutter clean
check:{{#tasks}} check_{{..snakeCase()}}{{/tasks}}
    flutter analyze

alias c := check
alias g := gen
alias l := lint

root := justfile_directory()
# end-header{{/justfile}}
# Tasks for {{name}}

# Generate bindings for {{name}}
gen_{{name.snakeCase()}}:
    cd /; flutter_rust_bridge_codegen -r "{{#mustacheCase}}root{{/mustacheCase}}/{{name}}/src/api.rs" -d "{{#mustacheCase}}root{{/mustacheCase}}/lib/src/{{name}}/{{bridge}}.dart"{{#ios}} -c "{{#mustacheCase}}root{{/mustacheCase}}/ios/Runner/{{bridge}}.{{name.snakeCase()}}.h"{{/ios}}{{#macos}} -c "{{#mustacheCase}}root{{/mustacheCase}}/macos/Runner/{{bridge}}.{{name.snakeCase()}}.h"{{/macos}}
lint_{{name.snakeCase()}}:
    cd {{name}} && cargo fmt
clean_{{name.snakeCase()}}:
    cd {{name}} && cargo clean
check_{{name.snakeCase()}}:
    cd {{name}} && cargo check
{{&previous_justfile}}